spring.application.name=mysql-demo
# mysql1 ? mysql ??????????? docker network
#spring.datasource.url=jdbc:mysql://10.211.55.10:3306/test?characterEncoding=utf-8
# mysql1
spring.datasource.url=jdbc:mysql://${MYSQL}:3306/test?characterEncoding=utf-8
# user1
spring.datasource.username=${USR}
# 123456
spring.datasource.password=${PWD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect