management:
  endpoints:
    web:
      exposure:
        include: prometheus #,metrics,health,info
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true